"""change personal_ID to BigInteger

Revision ID: 20f7a73fd680
Revises: 4b45dd2423bd
Create Date: 2024-12-06 12:26:49.984969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f7a73fd680'
down_revision = '4b45dd2423bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_details', schema=None) as batch_op:
        batch_op.alter_column('personal_ID',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_details', schema=None) as batch_op:
        batch_op.alter_column('personal_ID',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
