"""change audio tone to String

Revision ID: 57ba93d2cc33
Revises: 20f7a73fd680
Create Date: 2024-12-06 12:30:06.166041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ba93d2cc33'
down_revision = '20f7a73fd680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.alter_column('tone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.alter_column('tone',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
