"""add state subscription

Revision ID: 833fc360caab
Revises: 3f0163e045b2
Create Date: 2024-12-05 21:22:31.578820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833fc360caab'
down_revision = '3f0163e045b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
